export const articlesSeed = [
  {
    title: 'Mindset Belajar Excel dari Nol',
    slug: 'mindset-belajar-excel-dari-nol',
    excerpt: 'Mulai belajar Excel dari cara berpikir data, bukan dari menghafal rumus sebanyak mungkin.',
    content: 'Banyak pemula merasa Excel sulit karena langsung masuk ke rumus. Padahal sebelum rumus, kamu perlu memahami cara Excel melihat data: baris, kolom, tabel, dan hubungan antar nilai. Excel lebih mudah dipelajari jika kamu memulai dari struktur data, lalu tabel, lalu rumus, lalu studi kasus kerja.',
    category: 'Mindset Excel',
    level: 'Pemula',
  },
  {
    title: 'Mengenal Workbook, Worksheet, Cell, dan Range',
    slug: 'mengenal-workbook-worksheet-cell-dan-range',
    excerpt: 'Pahami bagian paling dasar Excel agar tidak bingung saat mulai membaca dan menulis data.',
    content: 'Workbook adalah file Excel yang kamu buka. Di dalam workbook ada worksheet atau sheet, yaitu halaman kerja tempat data ditulis. Cell adalah kotak tempat data berada, sedangkan range adalah kumpulan cell yang sering dipakai dalam rumus dan format tabel.',
    category: 'Dasar Excel',
    level: 'Pemula',
  },
  {
    title: 'Cara Membuat Tabel yang Rapi',
    slug: 'cara-membuat-tabel-yang-rapi',
    excerpt: 'Tabel yang rapi membuat filter, sort, rumus, pivot, dan dashboard jauh lebih mudah dibuat.',
    content: 'Tabel yang rapi selalu punya satu baris header, satu jenis data per kolom, dan tidak mencampur catatan bebas di tengah data. Kualitas tabel menentukan mudah atau sulitnya rumus yang akan kamu pakai.',
    category: 'Tabel dan Data',
    level: 'Dasar',
  },
  {
    title: 'Kesalahan Umum Pemula Saat Menggunakan Excel',
    slug: 'kesalahan-umum-pemula-saat-menggunakan-excel',
    excerpt: 'Kenali kebiasaan yang sering membuat file Excel sulit dirawat dan hasil rumus tidak akurat.',
    content: 'Pemula sering fokus pada tampilan, bukan struktur. Kesalahan umum yang perlu dihindari adalah merge cell di data mentah, tanggal berbentuk teks, menulis angka sebagai teks, dan menghapus kolom yang sudah dipakai rumus.',
    category: 'Mindset Excel',
    level: 'Dasar',
  },
  {
    title: 'Operator Matematika di Excel',
    slug: 'operator-matematika-di-excel',
    excerpt: 'Pelajari penjumlahan, pengurangan, perkalian, pembagian, dan urutan hitung dasar di Excel.',
    content: 'Operator matematika adalah dasar sebelum memakai fungsi seperti SUM dan AVERAGE. Kamu bisa menjumlahkan dengan +, mengurangi dengan -, mengalikan dengan *, dan membagi dengan /.',
    category: 'Rumus Dasar',
    level: 'Dasar',
  },
  {
    title: 'Rumus SUM dan AVERAGE untuk Pemula',
    slug: 'rumus-sum-dan-average-untuk-pemula',
    excerpt: 'Gunakan SUM dan AVERAGE untuk membuat rekap angka paling dasar dalam laporan kerja.',
    content: 'SUM digunakan untuk menjumlahkan angka dalam range. AVERAGE digunakan untuk menghitung nilai rata-rata. Dalam pekerjaan, keduanya sering dipakai untuk total omzet, jumlah stok, total jam kerja, dan rata-rata transaksi.',
    category: 'Rumus Dasar',
    level: 'Dasar',
  },
  {
    title: 'IF Dasar untuk Mengambil Keputusan',
    slug: 'if-dasar-untuk-mengambil-keputusan',
    excerpt: 'Gunakan IF untuk membuat label otomatis seperti tercapai, belum tercapai, lulus, atau perlu follow up.',
    content: 'IF dipakai saat kamu ingin Excel mengambil keputusan berdasarkan kondisi. Di dunia kerja, IF berguna untuk status target, status lulus, status telat, stok aman, atau lead yang perlu follow up ulang.',
    category: 'Logika Excel',
    level: 'Menengah',
  },
  {
    title: 'COUNTIF dan SUMIF untuk Rekap Data',
    slug: 'countif-dan-sumif-untuk-rekap-data',
    excerpt: 'Hitung dan jumlahkan data berdasarkan kriteria seperti sales, project, status, atau kategori produk.',
    content: 'COUNTIF dipakai untuk menghitung jumlah data yang memenuhi satu kriteria. SUMIF dipakai untuk menjumlahkan angka berdasarkan satu kriteria. Keduanya sering dipakai untuk laporan sales, status lead, dan omzet per project.',
    category: 'Rumus Dasar',
    level: 'Menengah',
  },
  {
    title: 'Cara Membaca Data dengan VLOOKUP dan XLOOKUP',
    slug: 'cara-membaca-data-dengan-vlookup-dan-xlookup',
    excerpt: 'Pahami konsep lookup untuk mencari data customer, harga produk, project, atau status berdasarkan kode tertentu.',
    content: 'Lookup dipakai saat kamu ingin mencari informasi berdasarkan kunci tertentu, misalnya kode produk, nomor customer, atau nama project. VLOOKUP umum dipakai di file lama, sedangkan XLOOKUP lebih modern dan fleksibel.',
    category: 'Logika Excel',
    level: 'Menengah',
  },
  {
    title: 'Studi Kasus Rekap Penjualan Sederhana',
    slug: 'studi-kasus-rekap-penjualan-sederhana',
    excerpt: 'Gabungkan konsep tabel, SUM, IF, COUNTIF, SUMIF, dan lookup dalam satu contoh laporan penjualan.',
    content: 'Studi kasus membantu kamu melihat bagaimana beberapa konsep Excel dipakai bersama. Dalam rekap penjualan, kamu mulai dari tabel transaksi, lalu membuat ringkasan omzet, jumlah closing, dan pencapaian target.',
    category: 'Studi Kasus Kerja',
    level: 'Menengah',
  },
]