export const excelTipsSeed = [
  {
    title: 'Total penjualan',
    slug: 'total-penjualan',
    category: 'rumus-bisnis',
    description: 'Menjumlahkan semua nilai penjualan dalam satu kolom.',
    formula: '=SUM(E2:E100)',
    useCase: 'Rekap omzet harian, mingguan, atau bulanan.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Rata-rata penjualan',
    slug: 'rata-rata-penjualan',
    category: 'rumus-bisnis',
    description: 'Menghitung nilai rata-rata transaksi dari daftar penjualan.',
    formula: '=AVERAGE(E2:E100)',
    useCase: 'Melihat kualitas transaksi atau average order value sederhana.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Jumlah transaksi',
    slug: 'jumlah-transaksi',
    category: 'rumus-bisnis',
    description: 'Menghitung jumlah baris transaksi yang terisi.',
    formula: '=COUNTA(A2:A100)',
    useCase: 'Audit data penjualan, booking, invoice, atau customer.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Total omzet per sales',
    slug: 'omzet-per-sales',
    category: 'rumus-bisnis',
    description: 'Menjumlahkan omzet berdasarkan nama sales tertentu.',
    formula: '=SUMIF(C:C;H2;E:E)',
    useCase: 'Leaderboard sales internal dan laporan performa tim.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Total omzet per project',
    slug: 'omzet-per-project',
    category: 'rumus-bisnis',
    description: 'Menjumlahkan omzet untuk project, cabang, atau produk tertentu.',
    formula: '=SUMIF(B:B;H2;E:E)',
    useCase: 'Laporan properti, cabang bisnis, atau kategori produk.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Jumlah closing',
    slug: 'jumlah-closing',
    category: 'rumus-bisnis',
    description: 'Menghitung berapa data yang statusnya Closing.',
    formula: '=COUNTIF(F:F;"Closing")',
    useCase: 'Monitoring pipeline sales dan hasil follow up.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Conversion rate lead ke booking',
    slug: 'conversion-lead-booking',
    category: 'rumus-bisnis',
    description: 'Mengukur persentase lead yang berubah menjadi booking.',
    formula: '=Booking/Leads',
    useCase: 'Evaluasi kualitas lead dari campaign iklan.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Conversion rate booking ke akad',
    slug: 'conversion-booking-akad',
    category: 'rumus-bisnis',
    description: 'Mengukur persentase booking yang lanjut menjadi akad.',
    formula: '=Akad/Booking',
    useCase: 'Analisis bottleneck sales properti atau produk high ticket.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'CPL / Cost per Lead',
    slug: 'cpl-cost-per-lead',
    category: 'rumus-bisnis',
    description: 'Menghitung biaya iklan untuk mendapatkan satu lead.',
    formula: '=Biaya_Iklan/Leads',
    useCase: 'Kontrol efisiensi Meta Ads, Google Ads, dan campaign digital.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'CPB / Cost per Booking',
    slug: 'cpb-cost-per-booking',
    category: 'rumus-bisnis',
    description: 'Menghitung biaya iklan untuk menghasilkan satu booking.',
    formula: '=Biaya_Iklan/Booking',
    useCase: 'Evaluasi campaign berdasarkan hasil yang lebih dekat ke revenue.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'CPA / Cost per Akad',
    slug: 'cpa-cost-per-akad',
    category: 'rumus-bisnis',
    description: 'Menghitung biaya iklan untuk menghasilkan satu akad atau transaksi final.',
    formula: '=Biaya_Iklan/Akad',
    useCase: 'Mengukur efisiensi campaign properti, kursus, dan produk mahal.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'ROAS',
    slug: 'roas',
    category: 'rumus-bisnis',
    description: 'Membandingkan omzet dengan biaya iklan.',
    formula: '=Omzet/Biaya_Iklan',
    useCase: 'Menentukan apakah campaign iklan layak dinaikkan budget.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Revenue per lead',
    slug: 'revenue-per-lead',
    category: 'rumus-bisnis',
    description: 'Mengukur rata-rata omzet yang dihasilkan dari setiap lead.',
    formula: '=Omzet/Leads',
    useCase: 'Membandingkan kualitas lead antar channel.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Target kurang berapa',
    slug: 'target-kurang-berapa',
    category: 'rumus-bisnis',
    description: 'Menghitung selisih target dengan realisasi saat ini.',
    formula: '=Target-Realisasi',
    useCase: 'Dashboard target sales, akad, leads, atau revenue.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Persentase pencapaian target',
    slug: 'persentase-target',
    category: 'rumus-bisnis',
    description: 'Menghitung progress realisasi terhadap target.',
    formula: '=Realisasi/Target',
    useCase: 'KPI dashboard dan laporan performa tim.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Status target',
    slug: 'status-target',
    category: 'rumus-bisnis',
    description: 'Memberi label apakah target sudah tercapai.',
    formula: '=IF(Realisasi>=Target;"Tercapai";"Belum Tercapai")',
    useCase: 'Laporan target otomatis yang mudah dibaca manajemen.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Laba kotor',
    slug: 'laba-kotor',
    category: 'rumus-bisnis',
    description: 'Menghitung selisih omzet dengan HPP.',
    formula: '=Omzet-HPP',
    useCase: 'Analisis profit produk, jasa, dan template digital.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Margin laba kotor',
    slug: 'margin-laba-kotor',
    category: 'rumus-bisnis',
    description: 'Menghitung persentase laba kotor terhadap omzet.',
    formula: '=(Omzet-HPP)/Omzet',
    useCase: 'Menentukan produk dengan margin paling sehat.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Laba bersih',
    slug: 'laba-bersih',
    category: 'rumus-bisnis',
    description: 'Menghitung omzet setelah dikurangi HPP dan biaya operasional.',
    formula: '=Omzet-HPP-Biaya_Operasional',
    useCase: 'Laporan laba rugi sederhana untuk UMKM.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Markup harga jual',
    slug: 'markup-harga-jual',
    category: 'rumus-bisnis',
    description: 'Menghitung kenaikan harga jual dari harga modal.',
    formula: '=(Harga_Jual-Harga_Modal)/Harga_Modal',
    useCase: 'Menentukan strategi pricing produk.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Harga setelah diskon',
    slug: 'harga-setelah-diskon',
    category: 'rumus-bisnis',
    description: 'Menghitung harga final setelah diskon persentase.',
    formula: '=Harga-(Harga*Diskon)',
    useCase: 'Promo, quotation, invoice, dan katalog produk.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Harga termasuk PPN',
    slug: 'harga-termasuk-ppn',
    category: 'rumus-bisnis',
    description: 'Menambahkan PPN ke harga dasar.',
    formula: '=Harga*(1+11%)',
    useCase: 'Invoice, quotation, dan simulasi harga.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Break even point unit',
    slug: 'bep-unit',
    category: 'rumus-bisnis',
    description: 'Menghitung unit minimal yang harus dijual agar balik modal.',
    formula: '=Biaya_Tetap/(Harga_Jual-HPP_Per_Unit)',
    useCase: 'Simulasi bisnis baru, produk digital, atau kelas Excel.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Arus kas bersih',
    slug: 'arus-kas-bersih',
    category: 'rumus-bisnis',
    description: 'Menghitung selisih kas masuk dan kas keluar.',
    formula: '=Kas_Masuk-Kas_Keluar',
    useCase: 'Cashflow bulanan dan monitoring kas bisnis.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'ROI',
    slug: 'roi',
    category: 'rumus-bisnis',
    description: 'Mengukur return dibanding modal investasi.',
    formula: '=(Keuntungan-Investasi)/Investasi',
    useCase: 'Evaluasi pembelian aset, campaign, dan project bisnis.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Cicilan flat sederhana',
    slug: 'cicilan-flat',
    category: 'rumus-bisnis',
    description: 'Menghitung cicilan flat dari harga, DP, margin, dan tenor.',
    formula: '=(Harga-DP+Margin)/Tenor_Bulan',
    useCase: 'Simulasi cicilan properti, pembiayaan, atau paket jasa.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Total margin syariah flat',
    slug: 'margin-syariah-flat',
    category: 'rumus-bisnis',
    description: 'Menghitung margin flat total berdasarkan pokok, margin tahunan, dan tenor.',
    formula: '=Pokok*Margin_Per_Tahun*Tenor_Tahun',
    useCase: 'Simulasi properti syariah dan pembiayaan tanpa bunga majemuk.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Cari data customer by WA',
    slug: 'customer-by-wa',
    category: 'rumus-bisnis',
    description: 'Mengambil data customer berdasarkan nomor WhatsApp.',
    formula: '=XLOOKUP(H2;D:D;A:F;"Tidak ditemukan")',
    useCase: 'CRM sederhana dari data leads dan customer.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Filter customer hot lead',
    slug: 'lead-hot',
    category: 'rumus-bisnis',
    description: 'Menampilkan hanya data lead dengan kategori Hot.',
    formula: '=FILTER(A:F;G:G="Hot")',
    useCase: 'Follow up prioritas untuk tim sales.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Lead masuk bulan ini',
    slug: 'lead-bulan-ini',
    category: 'rumus-bisnis',
    description: 'Menghitung lead yang masuk dalam bulan berjalan.',
    formula: '=COUNTIFS(A:A;">="&EOMONTH(TODAY();-1)+1;A:A;"<="&EOMONTH(TODAY();0))',
    useCase: 'Dashboard marketing bulanan.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Umur lead dalam hari',
    slug: 'umur-lead',
    category: 'rumus-bisnis',
    description: 'Menghitung berapa hari lead belum ditangani sejak masuk.',
    formula: '=TODAY()-A2',
    useCase: 'SLA follow up dan prioritas sales.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Top 10 lead terbaru',
    slug: 'top-10-lead-terbaru',
    category: 'rumus-bisnis',
    description: 'Mengurutkan data terbaru lalu mengambil 10 baris pertama.',
    formula: '=TAKE(SORT(DataSales;1;-1);10)',
    useCase: 'Dashboard lead terbaru untuk briefing harian.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'Progress target dashboard',
    slug: 'progress-target-dashboard',
    category: 'rumus-bisnis',
    description: 'Menampilkan progress target dalam format persen.',
    formula: '=TEXT(Realisasi/Target;"0%")',
    useCase: 'Card KPI dashboard agar cepat dibaca.',
    level: 'Pemula',
    tags: ['rumus-bisnis'],
  },
  {
    title: 'MARGIN',
    slug: 'lambda-margin',
    category: 'lambda',
    description: 'Fungsi custom untuk menghitung margin dari omzet dan HPP.',
    formula: '=LAMBDA(omzet;hpp;(omzet-hpp)/omzet)',
    useCase: 'Dipakai berulang di laporan produk dan sales.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'MARKUP',
    slug: 'lambda-markup',
    category: 'lambda',
    description: 'Fungsi custom untuk menghitung markup harga jual dari modal.',
    formula: '=LAMBDA(jual;modal;(jual-modal)/modal)',
    useCase: 'Pricing produk, paket jasa, dan template digital.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'LABABERSIH',
    slug: 'lambda-lababersih',
    category: 'lambda',
    description: 'Fungsi custom untuk menghitung laba bersih ringkas.',
    formula: '=LAMBDA(omzet;hpp;biaya;omzet-hpp-biaya)',
    useCase: 'Laporan laba rugi sederhana.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'CPL',
    slug: 'lambda-cpl',
    category: 'lambda',
    description: 'Fungsi custom untuk menghitung cost per lead.',
    formula: '=LAMBDA(biaya;leads;biaya/leads)',
    useCase: 'Evaluasi iklan harian atau mingguan.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'ROAS',
    slug: 'lambda-roas',
    category: 'lambda',
    description: 'Fungsi custom untuk menghitung return on ad spend.',
    formula: '=LAMBDA(omzet;biaya;omzet/biaya)',
    useCase: 'Monitoring performa campaign.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'CONVRATE',
    slug: 'lambda-convrate',
    category: 'lambda',
    description: 'Fungsi custom untuk menghitung conversion rate.',
    formula: '=LAMBDA(hasil;total;hasil/total)',
    useCase: 'Lead ke booking, booking ke akad, atau checkout ke order.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'CICILANFLAT',
    slug: 'lambda-cicilanflat',
    category: 'lambda',
    description: 'Fungsi custom untuk simulasi cicilan flat.',
    formula: '=LAMBDA(harga;dp;margin;tenor;(harga-dp+margin)/tenor)',
    useCase: 'Simulasi pembiayaan customer.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'MARGINSYARIAH',
    slug: 'lambda-marginsyariah',
    category: 'lambda',
    description: 'Fungsi custom untuk margin flat syariah.',
    formula: '=LAMBDA(pokok;margin_tahun;tenor_tahun;pokok*margin_tahun*tenor_tahun)',
    useCase: 'Perhitungan akad properti syariah.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'BEPUNIT',
    slug: 'lambda-bepunit',
    category: 'lambda',
    description: 'Fungsi custom untuk break even point unit.',
    formula: '=LAMBDA(biaya_tetap;harga;hpp;biaya_tetap/(harga-hpp))',
    useCase: 'Simulasi jumlah unit minimal agar balik modal.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'DISKONNET',
    slug: 'lambda-diskonnet',
    category: 'lambda',
    description: 'Fungsi custom untuk harga setelah diskon.',
    formula: '=LAMBDA(harga;diskon;harga-(harga*diskon))',
    useCase: 'Promo, invoice, dan quotation.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'PAJAK',
    slug: 'lambda-pajak',
    category: 'lambda',
    description: 'Fungsi custom untuk menghitung pajak dari tarif tertentu.',
    formula: '=LAMBDA(harga;tarif;harga*tarif)',
    useCase: 'PPN dan simulasi pajak sederhana.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'HARGAPPN',
    slug: 'lambda-hargappn',
    category: 'lambda',
    description: 'Fungsi custom untuk harga termasuk PPN.',
    formula: '=LAMBDA(harga;tarif;harga*(1+tarif))',
    useCase: 'Quotation dan invoice.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'UMURLEAD',
    slug: 'lambda-umurlead',
    category: 'lambda',
    description: 'Fungsi custom untuk menghitung umur lead dari tanggal masuk.',
    formula: '=LAMBDA(tgl;TODAY()-tgl)',
    useCase: 'Prioritas follow up lead.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'STATUSLEAD',
    slug: 'lambda-statuslead',
    category: 'lambda',
    description: 'Fungsi custom untuk memberi label Fresh, Warm, atau Cold.',
    formula: '=LAMBDA(tgl;IFS(TODAY()-tgl<=1;"Fresh";TODAY()-tgl<=7;"Warm";TRUE;"Cold"))',
    useCase: 'Segmentasi lead otomatis.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'BERSIHTEKS',
    slug: 'lambda-bersihteks',
    category: 'lambda',
    description: 'Fungsi custom untuk membersihkan spasi dan karakter tidak terlihat.',
    formula: '=LAMBDA(teks;TRIM(CLEAN(teks)))',
    useCase: 'Data customer, export marketplace, dan database lama.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'NAMARAPI',
    slug: 'lambda-namarapi',
    category: 'lambda',
    description: 'Fungsi custom untuk merapikan nama menjadi proper case.',
    formula: '=LAMBDA(teks;PROPER(TRIM(teks)))',
    useCase: 'Database customer dan peserta kelas.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'NOMORWA',
    slug: 'lambda-nomorwa',
    category: 'lambda',
    description: 'Fungsi custom untuk membersihkan spasi, strip, dan plus pada nomor WA.',
    formula: '=LAMBDA(no;SUBSTITUTE(SUBSTITUTE(SUBSTITUTE(no;" ";"");"-";"");"+";""))',
    useCase: 'Normalisasi nomor WhatsApp sebelum broadcast.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'STATUSCAPAIAN',
    slug: 'lambda-statuscapaian',
    category: 'lambda',
    description: 'Fungsi custom untuk memberi label target tercapai atau belum.',
    formula: '=LAMBDA(real;target;IF(real>=target;"Tercapai";"Belum Tercapai"))',
    useCase: 'Dashboard target sales dan tim.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'PERSENTARGET',
    slug: 'lambda-persentarget',
    category: 'lambda',
    description: 'Fungsi custom untuk menghitung persentase target.',
    formula: '=LAMBDA(real;target;real/target)',
    useCase: 'KPI bulanan dan laporan manajemen.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'KATEGORICPL',
    slug: 'lambda-kategoricpl',
    category: 'lambda',
    description: 'Fungsi custom untuk memberi kategori biaya lead.',
    formula: '=LAMBDA(cpl;IFS(cpl<=5000;"Bagus";cpl<=10000;"Sedang";TRUE;"Mahal"))',
    useCase: 'Audit campaign iklan per channel.',
    level: 'Pemula',
    tags: ['lambda'],
  },
  {
    title: 'Ambil angka',
    slug: 'regex-ambil-angka',
    category: 'regex',
    description: 'Pattern untuk mengambil angka dari teks campuran.',
    formula: '\\d+',
    useCase: 'Ekstrak nomor invoice, nominal, ID, atau kode.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil semua huruf',
    slug: 'regex-ambil-huruf',
    category: 'regex',
    description: 'Pattern untuk mengambil rangkaian huruf dari teks.',
    formula: '[A-Za-z]+',
    useCase: 'Membersihkan teks dari angka dan simbol.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil email',
    slug: 'regex-ambil-email',
    category: 'regex',
    description: 'Pattern untuk mengambil alamat email dari teks.',
    formula: '[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}',
    useCase: 'Ekstrak email dari notes, chat, atau export data.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Cek email sederhana',
    slug: 'regex-cek-email',
    category: 'regex',
    description: 'Pattern untuk validasi format email sederhana.',
    formula: '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$',
    useCase: 'Validasi list email sebelum campaign.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil nomor HP Indonesia',
    slug: 'regex-ambil-wa-indonesia',
    category: 'regex',
    description: 'Pattern nomor HP Indonesia dengan awalan +62, 62, atau 0.',
    formula: '(\\+62|62|0)8\\d{8,12}',
    useCase: 'Ekstrak nomor WA dari teks customer.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Cek nomor HP Indonesia',
    slug: 'regex-cek-wa-indonesia',
    category: 'regex',
    description: 'Pattern validasi nomor HP Indonesia.',
    formula: '^(\\+62|62|0)8\\d{8,12}$',
    useCase: 'Membersihkan database WhatsApp.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil tanggal dd/mm/yyyy',
    slug: 'regex-ambil-tanggal',
    category: 'regex',
    description: 'Pattern untuk mengambil tanggal format Indonesia.',
    formula: '\\d{1,2}/\\d{1,2}/\\d{4}',
    useCase: 'Ekstrak tanggal booking, jadwal, atau pembayaran.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil tahun',
    slug: 'regex-ambil-tahun',
    category: 'regex',
    description: 'Pattern untuk mengambil angka tahun empat digit.',
    formula: '\\b\\d{4}\\b',
    useCase: 'Ambil tahun dari kontrak atau catatan transaksi.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil nominal rupiah',
    slug: 'regex-nominal-rupiah',
    category: 'regex',
    description: 'Pattern untuk mengambil teks nominal dengan awalan Rp.',
    formula: 'Rp\\s?[\\d.]+',
    useCase: 'Ekstrak nominal dari chat atau keterangan pembayaran.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil angka desimal',
    slug: 'regex-angka-desimal',
    category: 'regex',
    description: 'Pattern untuk angka bulat atau desimal dengan koma/titik.',
    formula: '\\d+([.,]\\d+)?',
    useCase: 'Ambil angka target, rate, dan nominal desimal.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil teks dalam kurung',
    slug: 'regex-teks-dalam-kurung',
    category: 'regex',
    description: 'Pattern untuk mengambil isi di dalam tanda kurung.',
    formula: '\\((.*?)\\)',
    useCase: 'Ambil keterangan tambahan dari nama produk atau project.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil hashtag',
    slug: 'regex-hashtag',
    category: 'regex',
    description: 'Pattern untuk mengambil hashtag dari caption.',
    formula: '#[A-Za-z0-9_]+',
    useCase: 'Analisis caption sosial media.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil username',
    slug: 'regex-username',
    category: 'regex',
    description: 'Pattern untuk mengambil username dengan awalan @.',
    formula: '@[A-Za-z0-9_.]+',
    useCase: 'Ekstrak username Instagram atau TikTok.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil URL',
    slug: 'regex-url',
    category: 'regex',
    description: 'Pattern untuk mengambil link dari teks panjang.',
    formula: 'https?://[^\\s]+',
    useCase: 'Membersihkan data link dari chat atau notes.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Cek kode pos Indonesia',
    slug: 'regex-kode-pos',
    category: 'regex',
    description: 'Pattern validasi kode pos lima digit.',
    formula: '^\\d{5}$',
    useCase: 'Validasi alamat customer atau pengiriman.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Cek hanya angka',
    slug: 'regex-hanya-angka',
    category: 'regex',
    description: 'Pattern untuk memastikan teks hanya angka.',
    formula: '^\\d+$',
    useCase: 'Validasi ID, NIK sederhana, atau nomor transaksi.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Cek hanya huruf',
    slug: 'regex-hanya-huruf',
    category: 'regex',
    description: 'Pattern untuk memastikan input hanya huruf dan spasi.',
    formula: '^[A-Za-z\\s]+$',
    useCase: 'Validasi nama tanpa angka/simbol.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Hapus semua selain angka',
    slug: 'regex-hapus-selain-angka',
    category: 'regex',
    description: 'Pattern untuk menghapus karakter non-angka.',
    formula: '[^\\d]',
    useCase: 'Membersihkan nomor WA, NIK, atau nominal.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Hapus semua selain huruf',
    slug: 'regex-hapus-selain-huruf',
    category: 'regex',
    description: 'Pattern untuk menghapus angka dan simbol.',
    formula: '[^A-Za-z\\s]',
    useCase: 'Membersihkan nama atau kota.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Hapus spasi berlebih',
    slug: 'regex-spasi-berlebih',
    category: 'regex',
    description: 'Pattern untuk menyatukan banyak spasi menjadi satu.',
    formula: '\\s+',
    useCase: 'Merapikan teks hasil copy paste.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil kata pertama',
    slug: 'regex-kata-pertama',
    category: 'regex',
    description: 'Pattern untuk mengambil kata di awal teks.',
    formula: '^\\w+',
    useCase: 'Ambil nama depan atau kode awal.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil kata terakhir',
    slug: 'regex-kata-terakhir',
    category: 'regex',
    description: 'Pattern untuk mengambil kata di akhir teks.',
    formula: '\\w+$',
    useCase: 'Ambil nama belakang atau status terakhir.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Cek kata syariah',
    slug: 'regex-kata-syariah',
    category: 'regex',
    description: 'Pattern case-insensitive untuk mencari kata syariah.',
    formula: '(?i)syariah',
    useCase: 'Klasifikasi produk atau project syariah.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil kode invoice',
    slug: 'regex-kode-invoice',
    category: 'regex',
    description: 'Pattern untuk kode invoice berformat INV-angka.',
    formula: 'INV-\\d+',
    useCase: 'Rekonsiliasi invoice dari marketplace atau sistem.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil kode booking',
    slug: 'regex-kode-booking',
    category: 'regex',
    description: 'Pattern untuk kode booking dengan prefiks BK-.',
    formula: 'BK-[A-Z0-9]+',
    useCase: 'Cocokkan data booking dengan CRM.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Cek plat nomor sederhana',
    slug: 'regex-plat-nomor',
    category: 'regex',
    description: 'Pattern sederhana untuk plat nomor kendaraan Indonesia.',
    formula: '^[A-Z]{1,2}\\s?\\d{1,4}\\s?[A-Z]{1,3}$',
    useCase: 'Validasi data kendaraan operasional.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil angka setelah kata DP',
    slug: 'regex-angka-setelah-dp',
    category: 'regex',
    description: 'Pattern untuk menangkap nilai setelah kata DP.',
    formula: 'DP\\s?(\\d+)',
    useCase: 'Ekstrak DP dari chat sales.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil harga rupiah',
    slug: 'regex-harga-rupiah',
    category: 'regex',
    description: 'Pattern untuk mengambil harga setelah kata Harga.',
    formula: 'Harga\\s?Rp?\\s?[\\d.]+',
    useCase: 'Ekstrak harga dari notes produk.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ambil domain email',
    slug: 'regex-domain-email',
    category: 'regex',
    description: 'Pattern untuk mengambil domain dari alamat email.',
    formula: '@([A-Za-z0-9.-]+)',
    useCase: 'Segmentasi email perusahaan atau personal.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Validasi password sederhana',
    slug: 'regex-password-sederhana',
    category: 'regex',
    description: 'Pattern minimal 8 karakter, mengandung huruf dan angka.',
    formula: '^(?=.*[A-Za-z])(?=.*\\d).{8,}$',
    useCase: 'Validasi data akun internal sederhana.',
    level: 'Pemula',
    tags: ['regex'],
  },
  {
    title: 'Ubah data jadi Excel Table',
    slug: 'struktur-data-table',
    category: 'tips-trick',
    description: 'Gunakan Ctrl + T agar range otomatis bertambah saat data baru masuk.',
    formula: 'Ctrl + T',
    useCase: 'Database leads, sales, inventory, dan laporan rutin.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Aktifkan filter cepat',
    slug: 'aktifkan-filter',
    category: 'tips-trick',
    description: 'Menyalakan filter tanpa klik menu ribbon.',
    formula: 'Ctrl + Shift + L',
    useCase: 'Menyaring data customer, project, status, dan sales.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Pilih kolom atau baris cepat',
    slug: 'pilih-kolom-baris',
    category: 'tips-trick',
    description: 'Gunakan shortcut untuk memilih kolom atau baris penuh.',
    formula: 'Ctrl + Space / Shift + Space',
    useCase: 'Editing kolom laporan besar tanpa drag manual.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Lompat ke ujung data',
    slug: 'lompat-ujung-data',
    category: 'tips-trick',
    description: 'Berpindah cepat ke batas data aktif.',
    formula: 'Ctrl + Arrow',
    useCase: 'Navigasi sheet besar ribuan baris.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Blok data cepat',
    slug: 'blok-data-cepat',
    category: 'tips-trick',
    description: 'Memblok area data dari posisi aktif sampai ujung data.',
    formula: 'Ctrl + Shift + Arrow',
    useCase: 'Select range sebelum format, copy, atau chart.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Isi tanggal hari ini',
    slug: 'tanggal-hari-ini',
    category: 'tips-trick',
    description: 'Shortcut untuk mengisi tanggal hari ini.',
    formula: 'Ctrl + ;',
    useCase: 'Log follow up, absensi, dan pembayaran.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Isi jam sekarang',
    slug: 'jam-sekarang',
    category: 'tips-trick',
    description: 'Shortcut untuk mengisi jam saat ini.',
    formula: 'Ctrl + Shift + ;',
    useCase: 'Log aktivitas dan update status.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'AutoSum cepat',
    slug: 'autosum',
    category: 'tips-trick',
    description: 'Menjumlahkan range angka tanpa mengetik formula manual.',
    formula: 'Alt + =',
    useCase: 'Subtotal, rekap, dan laporan cepat.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Kunci referensi formula',
    slug: 'kunci-referensi',
    category: 'tips-trick',
    description: 'Mengubah A1 menjadi $A$1 saat menulis rumus.',
    formula: 'F4',
    useCase: 'Formula target, kurs, pajak, dan parameter tetap.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Buka Format Cells',
    slug: 'format-cells',
    category: 'tips-trick',
    description: 'Membuka pengaturan format angka, tanggal, alignment, dan proteksi.',
    formula: 'Ctrl + 1',
    useCase: 'Rapikan laporan sebelum dikirim.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Flash Fill',
    slug: 'flash-fill',
    category: 'tips-trick',
    description: 'Mengisi pola otomatis berdasarkan contoh.',
    formula: 'Ctrl + E',
    useCase: 'Pisah nama, ambil kode, atau rapikan format teks.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Copy dari atas atau kiri',
    slug: 'copy-dari-atas-kiri',
    category: 'tips-trick',
    description: 'Mengisi sel aktif dari data atas atau kiri.',
    formula: 'Ctrl + D / Ctrl + R',
    useCase: 'Input data berulang di tabel kerja.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Pindah sheet cepat',
    slug: 'pindah-sheet',
    category: 'tips-trick',
    description: 'Navigasi antar worksheet tanpa mouse.',
    formula: 'Ctrl + Page Up / Ctrl + Page Down',
    useCase: 'Workbook dengan banyak sheet laporan.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Find dan Replace',
    slug: 'find-replace',
    category: 'tips-trick',
    description: 'Mencari dan mengganti teks dalam workbook.',
    formula: 'Ctrl + F / Ctrl + H',
    useCase: 'Perbaiki nama project, status, atau kode yang salah.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Buat Pivot Table',
    slug: 'buat-pivot-table',
    category: 'tips-trick',
    description: 'Shortcut ribbon untuk membuat Pivot Table.',
    formula: 'Alt + N + V',
    useCase: 'Ringkasan sales, stok, leads, dan pembayaran.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Jangan merge cell data mentah',
    slug: 'jangan-merge-data-mentah',
    category: 'tips-trick',
    description: 'Merge cell membuat filter, sort, pivot, dan formula sering bermasalah.',
    formula: 'Hindari Merge Cells',
    useCase: 'Database operasional yang akan dianalisis.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Pakai Data Validation untuk status',
    slug: 'data-validation-status',
    category: 'tips-trick',
    description: 'Buat dropdown agar input status konsisten.',
    formula: 'Data > Data Validation',
    useCase: 'Status Follow Up, Booking, Akad, Ghosting.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Remove Duplicates untuk nomor WA',
    slug: 'remove-duplicates-wa',
    category: 'tips-trick',
    description: 'Hapus data ganda berdasarkan nomor WhatsApp.',
    formula: 'Data > Remove Duplicates',
    useCase: 'Membersihkan database customer sebelum broadcast.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Tandai lead telat follow up',
    slug: 'conditional-follow-up',
    category: 'tips-trick',
    description: 'Gunakan Conditional Formatting untuk lead lebih dari 3 hari.',
    formula: 'Conditional Formatting + TODAY()-Tanggal>=3',
    useCase: 'SLA follow up tim sales.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Pisahkan input dan dashboard',
    slug: 'pisah-input-dashboard',
    category: 'tips-trick',
    description: 'Simpan database utama di satu sheet dan dashboard di sheet berbeda.',
    formula: 'DataSales + Dashboard',
    useCase: 'Workbook bisnis yang lebih aman dan mudah dirawat.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Dashboard satu layar',
    slug: 'dashboard-satu-layar',
    category: 'tips-trick',
    description: 'Buat dashboard ringkas, tidak terlalu ramai, dan fokus KPI utama.',
    formula: 'Leads + CPL + Booking + Akad + Omzet + ROAS',
    useCase: 'Dashboard marketing dan sales bulanan.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Backup mingguan file bisnis',
    slug: 'backup-mingguan',
    category: 'tips-trick',
    description: 'Simpan salinan rutin dan manfaatkan version history cloud.',
    formula: 'OneDrive / Google Drive Version History',
    useCase: 'File sales, pembayaran, inventory, dan payroll.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Protect Sheet untuk rumus',
    slug: 'protect-sheet-rumus',
    category: 'tips-trick',
    description: 'Kunci area formula agar tidak rusak saat dipakai tim.',
    formula: 'Review > Protect Sheet',
    useCase: 'Template kerja yang dipakai banyak orang.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
  {
    title: 'Buat sheet README',
    slug: 'sheet-readme',
    category: 'tips-trick',
    description: 'Dokumentasikan arti kolom dan cara pakai workbook.',
    formula: 'Sheet README',
    useCase: 'Template bisnis yang dipakai tim atau customer.',
    level: 'Pemula',
    tags: ['tips-trick'],
  },
]
