export const videosSeed = [
  {
    title: 'Modul 1 - Berkenalan dengan Excel',
    slug: 'modul-1-berkenalan-dengan-excel',
    description: 'Materi Pengenalan Excel dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=75xRDnyoJC8',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 1,
    level: 'Pemula',
    durationLabel: '17:57',
    isExclusive: false,
  },
  {
    title: 'MODUL 2.1 - CARA MENGISI CELL DI EXCEL',
    slug: 'modul-2-1-cara-mengisi-cell-di-excel',
    description: 'Materi Dasar Excel dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=X3ngqk7UH8Y',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 2,
    level: 'Pemula',
    durationLabel: '13:57',
    isExclusive: false,
  },
  {
    title: 'Modul 2.2 - Aturan dalam membuat table di excel',
    slug: 'modul-2-2-aturan-membuat-table-di-excel',
    description: 'Materi Dasar Tabel dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=_lawDmV1u6Q',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 3,
    level: 'Pemula',
    durationLabel: '22:16',
    isExclusive: false,
  },
  {
    title: 'MODUL 2.3 - MEMBUAT TABLE PERTAMA YANG PROPPER',
    slug: 'modul-2-3-membuat-table-pertama-yang-proper',
    description: 'Materi Dasar Tabel dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=xuUkVgjiWcI',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 4,
    level: 'Pemula',
    durationLabel: '33:40',
    isExclusive: false,
  },
  {
    title: 'MODUL 3.1 - JENIS JENIS ERROR DI EXCEL',
    slug: 'modul-3-1-jenis-jenis-error-di-excel',
    description: 'Materi Error Excel dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=Q8f4raLYVog',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 5,
    level: 'Pemula',
    durationLabel: '7:06',
    isExclusive: false,
  },
  {
    title: 'MODUL 3.2 - OPERATOR MATEMATIKA',
    slug: 'modul-3-2-operator-matematika',
    description: 'Materi Operator Matematika dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=cQMG3ODKh44',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 6,
    level: 'Pemula',
    durationLabel: '23:32',
    isExclusive: false,
  },
  {
    title: 'MODUL 4.1 PART 1 - MENGUASAI RUMUS SUM SAMPE AKARNYA',
    slug: 'modul-4-1-part-1-menguasai-rumus-sum',
    description: 'Materi Rumus Dasar dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=9iYinE-Rsts',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 7,
    level: 'Dasar',
    durationLabel: '22:06',
    isExclusive: false,
  },
  {
    title: 'MODUL 4.1 PART 2 - FUNGSI SUMPRODUCT, PRODUCT, MODE.MULT, MODE.SGL, MOD, QUOTIENT',
    slug: 'modul-4-1-part-2-sumproduct-product-mode-mod-quotient',
    description: 'Materi Rumus Matematika dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=6IG7W3CqSEQ',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 8,
    level: 'Dasar',
    durationLabel: '17:00',
    isExclusive: false,
  },
  {
    title: 'MODUL 4.2 - PEMBULATAN',
    slug: 'modul-4-2-pembulatan',
    description: 'Materi Rumus Matematika dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=URY2cilSgA4',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 9,
    level: 'Dasar',
    durationLabel: '28:11',
    isExclusive: false,
  },
  {
    title: 'MODUL 5.1 - MIN, MAX, MEDIAN',
    slug: 'modul-5-1-min-max-median',
    description: 'Materi Statistik Dasar dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=StWcFa18v0k',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 10,
    level: 'Dasar',
    durationLabel: '15:02',
    isExclusive: false,
  },
  {
    title: 'MODUL 5.2 - AVERAGE, COUNT, COUNTA, COUNTBLANK',
    slug: 'modul-5-2-average-count-counta-countblank',
    description: 'Materi Statistik Dasar dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=UORJOUCqdn0',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 11,
    level: 'Dasar',
    durationLabel: '7:51',
    isExclusive: false,
  },
  {
    title: 'MODUL 5.3 - COUNTIFS, SUMIFS, AVERAGEIFS, MINIFS, MAXIFS',
    slug: 'modul-5-3-countifs-sumifs-averageifs-minifs-maxifs',
    description: 'Materi Rumus Bersyarat dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=gDt1spwS7PI',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 12,
    level: 'Menengah',
    durationLabel: '9:17',
    isExclusive: false,
  },
  {
    title: 'MODUL 5.4 - WILD CARD',
    slug: 'modul-5-4-wild-card',
    description: 'Materi Rumus Bersyarat dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=1bo5ZMovJ0o',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 13,
    level: 'Menengah',
    durationLabel: '20:56',
    isExclusive: false,
  },
  {
    title: 'MODUL 6.1 - IF, IFS, SWITCH, CHOOSE',
    slug: 'modul-6-1-if-ifs-switch-choose',
    description: 'Materi Logika Excel dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=5tBbTO8s73M',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 14,
    level: 'Menengah',
    durationLabel: '19:03',
    isExclusive: false,
  },
  {
    title: 'MODUL 6.2 - AND, OR, XOR, NOT, LOGIKA ALJABAR',
    slug: 'modul-6-2-and-or-xor-not-logika-aljabar',
    description: 'Materi Logika Excel dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=PxAbvCbmvKg',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 15,
    level: 'Menengah',
    durationLabel: '19:30',
    isExclusive: false,
  },
  {
    title: 'MODUL 6.3 - IS LOGICAL',
    slug: 'modul-6-3-is-logical',
    description: 'Materi Logika Excel dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=oTTjIz07sQI',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 16,
    level: 'Menengah',
    durationLabel: '7:25',
    isExclusive: false,
  },
  {
    title: 'MODUL 7.2 - TEXT FUNCTION',
    slug: 'modul-7-2-text-function',
    description: 'Materi Text Function dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=wBPelAIZyr8',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 17,
    level: 'Menengah',
    durationLabel: '17:08',
    isExclusive: false,
  },
  {
    title: 'MODUL 7.3 - TEXTSPLIT, TEXTBEFORE, TEXTAFTER, TEXTJOIN',
    slug: 'modul-7-3-textsplit-textbefore-textafter-textjoin',
    description: 'Materi Text Function dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=Eyt9woBhm7Y',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 18,
    level: 'Menengah',
    durationLabel: '20:38',
    isExclusive: false,
  },
  {
    title: 'MODUL 8.1 - PART 1 - OPENING DAN PENJELASAN LOOKUP SERIES',
    slug: 'modul-8-1-part-1-opening-lookup-series',
    description: 'Materi Lookup dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=4RseruR0MGA',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 19,
    level: 'Menengah',
    durationLabel: '17:12',
    isExclusive: false,
  },
  {
    title: 'MODUL 8.1 - VLOOKUP, XLOOKUP, INDEX MATCH',
    slug: 'modul-8-1-vlookup-xlookup-index-match',
    description: 'Materi Lookup dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=PfiCdn2Jl5o',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 20,
    level: 'Menengah',
    durationLabel: '53:05',
    isExclusive: false,
  },
  {
    title: 'MODUL 8.2 - LOOKUP DATA TERAKHIR',
    slug: 'modul-8-2-lookup-data-terakhir',
    description: 'Materi Lookup dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=Wpsj9SWsGKE',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 21,
    level: 'Menengah',
    durationLabel: '8:17',
    isExclusive: false,
  },
  {
    title: 'MODUL 8.3 - Bukan Cuma MATCH, INDEX Punya Kekuatan Tersembunyi! Simak Tutorialnya',
    slug: 'modul-8-3-kekuatan-index-match',
    description: 'Materi Lookup dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=2og7cyQUX-k',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 22,
    level: 'Menengah',
    durationLabel: '21:56',
    isExclusive: false,
  },
  {
    title: 'MODUL 8.4 - PENYEBAB ERROR #N/A VLOOKUP',
    slug: 'modul-8-4-penyebab-error-na-vlookup',
    description: 'Materi Lookup dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=J3F8F89JpLA',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 23,
    level: 'Menengah',
    durationLabel: '10:14',
    isExclusive: false,
  },
  {
    title: 'MODUL - 9,1 DATE, DAY, MONTH, YEAR, TODAY, NOW',
    slug: 'modul-9-1-date-day-month-year-today-now',
    description: 'Materi Date & Time dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=yxdApAY5uIk',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 24,
    level: 'Menengah',
    durationLabel: '16:10',
    isExclusive: false,
  },
  {
    title: 'MODUL 9,2  DATEDIF, DAYS, EDATE',
    slug: 'modul-9-2-datedif-days-edate',
    description: 'Materi Date & Time dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=-wRnsiPuuRg',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 25,
    level: 'Menengah',
    durationLabel: '15:31',
    isExclusive: false,
  },
  {
    title: 'MODUL 9.3 - WORKDAY, WORKDAY.INTL, NETWORKDAY, NETWORKDAY.INTL, WEEKNUM, ISOWEEKNUM',
    slug: 'modul-9-3-workday-networkday-weeknum-isoweeknum',
    description: 'Materi Date & Time dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=uVM7IH2Lod4',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 26,
    level: 'Menengah',
    durationLabel: '30:14',
    isExclusive: false,
  },
  {
    title: 'MODUL 9.4 - STUDY KASUS DATE',
    slug: 'modul-9-4-study-kasus-date',
    description: 'Materi Date & Time dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=FtEwuURKDCk',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 27,
    level: 'Menengah',
    durationLabel: '13:33',
    isExclusive: false,
  },
  {
    title: 'MODUL 10.1 BOCORAN SOAL TEST EXCEL CALON MANAGER SALES',
    slug: 'modul-10-1-soal-test-excel-calon-manager-sales',
    description: 'Materi Studi Kasus Kerja dari program Belajar Excel dari Nol - E Course. Ikuti video sampai selesai, lalu lanjutkan ke materi berikutnya atau coba Test Excel terkait.',
    youtubeUrl: 'https://www.youtube.com/watch?v=sNTeQMsBag4',
    youtubePlaylistUrl: 'https://www.youtube.com/playlist?list=PLNZ8iqpnPoyEziIGVjl8Nu7Sv_t0k7IP2',
    orderIndex: 28,
    level: 'Professional',
    durationLabel: '29:05',
    isExclusive: false,
  },
]
