export const ROUTES = {
  HOME: '/',

  LEARN: '/belajar',
  LEARN_DETAIL: (slug: string) => `/belajar/${slug}`,

  VIDEO: '/video',
  VIDEO_DETAIL: (slug: string) => `/video/${slug}`,

  TEST_EXCEL: '/test-excel',
  TEST_EXCEL_DETAIL: (slug: string) => `/test-excel/${slug}`,
  TEST_EXCEL_PLAY: (slug: string) => `/test-excel/${slug}/play`,
  TEST_EXCEL_RESULT: (slug: string) => `/test-excel/${slug}/hasil`,
  TEST_EXCEL_ANSWER: (slug: string) => `/test-excel/${slug}/jawaban`,
  TEST_EXCEL_TUTORIAL: (slug: string) => `/test-excel/${slug}/tutorial`,

  CHALLENGE: '/challenge',
  CHALLENGE_DETAIL: (slug: string) => `/challenge/${slug}`,
  CHALLENGE_PLAY: (slug: string) => `/challenge/${slug}/play`,

  PRACTICE: '/test-excel',
  PRACTICE_DETAIL: (slug: string) => `/test-excel/${slug}`,
  PRACTICE_EXPLANATION: (slug: string) => `/test-excel/${slug}/jawaban`,

  STUDI_KASUS: '/studi-kasus',
  STUDI_KASUS_DETAIL: (slug: string) => `/studi-kasus/${slug}`,

  EXCEL_TIPS: '/excel-tips',
  EXCEL_TIP_DETAIL: (slug: string) => `/excel-tips/${slug}`,

  TIPS: '/tips',
  BUSINESS_FORMULAS: '/tips/rumus-bisnis',
  LAMBDA_DICTIONARY: '/tips/lambda',
  REGEX_PATTERNS: '/tips/regex',
  TIPS_TRICK: '/tips/trick',
  TIP_DETAIL: (slug: string) => `/excel-tips/${slug}`,

  TEMPLATES: '/template',
  TEMPLATE_DETAIL: (slug: string) => `/template/${slug}`,

  CLASSES: '/kelas',
  CLASS_ONLINE: '/kelas/online',
  CLASS_OFFLINE: '/kelas/offline',
  CLASS_PRIVATE: '/kelas/private',

  CONTACT: '/kontak',
  INHOUSE: '/inhouse',
  CERTIFICATES: '/certificate',
  CERTIFICATE_DETAIL: (id: string) => `/certificate/${id}`,
  PORTFOLIO: '/portfolio',
  PORTFOLIO_DETAIL: (username: string) => `/portfolio/${username}`,

  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/lupa-password',
  RESET_PASSWORD: '/reset-password',
  VERIFY_EMAIL: '/verifikasi-email',

  DASHBOARD: '/dashboard',
  PROFILE: '/profile',
  PROFILE_PUBLIC: (username: string) => `/profile/${username}`,
  PROFILE_PORTFOLIO: (username: string) => `/profile/${username}/portfolio`,
  PROFILE_CERTIFICATE: (username: string) => `/profile/${username}/certificate`,
  PROFILE_CERTIFICATE_DETAIL: (username: string, id: string) => `/profile/${username}/certificate/${id}`,
  MY_COURSES: '/dashboard/kursus-saya',
  PROGRESS: '/dashboard/progress',
  BOOKMARKS: '/dashboard/bookmark',
  SETTINGS: '/dashboard/pengaturan',

  ADMIN: '/admin',
  ADMIN_COURSES: '/admin/kursus',
  ADMIN_EXCEL_TIPS: '/admin/excel-tips',
  ADMIN_QUIZZES: '/admin/quiz',
  ADMIN_USERS: '/admin/users',
  ADMIN_PAYMENTS: '/admin/transaksi',
  ADMIN_ANALYTICS: '/admin/analytics',

  PRICING: '/harga',
  ECOSYSTEM: '/ekosistem',
  CAREER: '/karir',
  ABOUT: '/tentang',
  LEADERBOARD: '/leaderboard',

  COURSES: '/belajar',
  COURSE_DETAIL: (slug: string) => `/belajar/${slug}`,
  COMPETITION: '/test-excel',
  RANKED_MATCH: '/test-excel',
  TRAINING_ARENA: '/challenge',
  DAILY_QUIZ: '/test-excel',

  LEGACY_COURSES: '/kursus',
  LEGACY_COURSE_DETAIL: (slug: string) => `/kursus/${slug}`,
  LEGACY_VIDEOS: '/video-pembelajaran',
  LEGACY_EXCEL_TIPS: '/tips',
  LEGACY_EXCEL_TIP_DETAIL: (slug: string) => `/tips/${slug}`,
  LEGACY_PRACTICE: '/latihan',
  LEGACY_PRACTICE_DETAIL: (slug: string) => `/latihan/${slug}`,
  LEGACY_PRACTICE_EXPLANATION: (slug: string) => `/latihan/${slug}/penjelasan`,
  LEGACY_COMPETITION: '/kompetisi',
  LEGACY_RANKED_MATCH: '/kompetisi/ranked-match',
  LEGACY_TRAINING_ARENA: '/kompetisi/training-arena',
  LEGACY_DAILY_QUIZ: '/kompetisi/kuis-harian',
  LEGACY_ESPORTS: '/esports',
  LEGACY_ESPORTS_RANKED_MATCH: '/esports/ranked-match',
  LEGACY_ESPORTS_TRAINING_ARENA: '/esports/training-arena',
  LEGACY_ESPORTS_DAILY_QUIZ: '/esports/daily-quiz',
} as const